/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Leccion } from "./Leccion";
import { LeccionCountArgs } from "./LeccionCountArgs";
import { LeccionFindManyArgs } from "./LeccionFindManyArgs";
import { LeccionFindUniqueArgs } from "./LeccionFindUniqueArgs";
import { DeleteLeccionArgs } from "./DeleteLeccionArgs";
import { LeccionService } from "../leccion.service";
@graphql.Resolver(() => Leccion)
export class LeccionResolverBase {
  constructor(protected readonly service: LeccionService) {}

  async _leccionsMeta(
    @graphql.Args() args: LeccionCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Leccion])
  async leccions(
    @graphql.Args() args: LeccionFindManyArgs
  ): Promise<Leccion[]> {
    return this.service.leccions(args);
  }

  @graphql.Query(() => Leccion, { nullable: true })
  async leccion(
    @graphql.Args() args: LeccionFindUniqueArgs
  ): Promise<Leccion | null> {
    const result = await this.service.leccion(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Leccion)
  async deleteLeccion(
    @graphql.Args() args: DeleteLeccionArgs
  ): Promise<Leccion | null> {
    try {
      return await this.service.deleteLeccion(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
