/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { ArticuloTecnico } from "./ArticuloTecnico";
import { ArticuloTecnicoCountArgs } from "./ArticuloTecnicoCountArgs";
import { ArticuloTecnicoFindManyArgs } from "./ArticuloTecnicoFindManyArgs";
import { ArticuloTecnicoFindUniqueArgs } from "./ArticuloTecnicoFindUniqueArgs";
import { DeleteArticuloTecnicoArgs } from "./DeleteArticuloTecnicoArgs";
import { ArticuloTecnicoService } from "../articuloTecnico.service";
@graphql.Resolver(() => ArticuloTecnico)
export class ArticuloTecnicoResolverBase {
  constructor(protected readonly service: ArticuloTecnicoService) {}

  async _articuloTecnicosMeta(
    @graphql.Args() args: ArticuloTecnicoCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [ArticuloTecnico])
  async articuloTecnicos(
    @graphql.Args() args: ArticuloTecnicoFindManyArgs
  ): Promise<ArticuloTecnico[]> {
    return this.service.articuloTecnicos(args);
  }

  @graphql.Query(() => ArticuloTecnico, { nullable: true })
  async articuloTecnico(
    @graphql.Args() args: ArticuloTecnicoFindUniqueArgs
  ): Promise<ArticuloTecnico | null> {
    const result = await this.service.articuloTecnico(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => ArticuloTecnico)
  async deleteArticuloTecnico(
    @graphql.Args() args: DeleteArticuloTecnicoArgs
  ): Promise<ArticuloTecnico | null> {
    try {
      return await this.service.deleteArticuloTecnico(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
