/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Aplicacion } from "./Aplicacion";
import { AplicacionCountArgs } from "./AplicacionCountArgs";
import { AplicacionFindManyArgs } from "./AplicacionFindManyArgs";
import { AplicacionFindUniqueArgs } from "./AplicacionFindUniqueArgs";
import { DeleteAplicacionArgs } from "./DeleteAplicacionArgs";
import { AplicacionService } from "../aplicacion.service";
@graphql.Resolver(() => Aplicacion)
export class AplicacionResolverBase {
  constructor(protected readonly service: AplicacionService) {}

  async _aplicacionsMeta(
    @graphql.Args() args: AplicacionCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Aplicacion])
  async aplicacions(
    @graphql.Args() args: AplicacionFindManyArgs
  ): Promise<Aplicacion[]> {
    return this.service.aplicacions(args);
  }

  @graphql.Query(() => Aplicacion, { nullable: true })
  async aplicacion(
    @graphql.Args() args: AplicacionFindUniqueArgs
  ): Promise<Aplicacion | null> {
    const result = await this.service.aplicacion(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Aplicacion)
  async deleteAplicacion(
    @graphql.Args() args: DeleteAplicacionArgs
  ): Promise<Aplicacion | null> {
    try {
      return await this.service.deleteAplicacion(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
