/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { DocumentacionTecnica } from "./DocumentacionTecnica";
import { DocumentacionTecnicaCountArgs } from "./DocumentacionTecnicaCountArgs";
import { DocumentacionTecnicaFindManyArgs } from "./DocumentacionTecnicaFindManyArgs";
import { DocumentacionTecnicaFindUniqueArgs } from "./DocumentacionTecnicaFindUniqueArgs";
import { DeleteDocumentacionTecnicaArgs } from "./DeleteDocumentacionTecnicaArgs";
import { DocumentacionTecnicaService } from "../documentacionTecnica.service";
@graphql.Resolver(() => DocumentacionTecnica)
export class DocumentacionTecnicaResolverBase {
  constructor(protected readonly service: DocumentacionTecnicaService) {}

  async _documentacionTecnicasMeta(
    @graphql.Args() args: DocumentacionTecnicaCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [DocumentacionTecnica])
  async documentacionTecnicas(
    @graphql.Args() args: DocumentacionTecnicaFindManyArgs
  ): Promise<DocumentacionTecnica[]> {
    return this.service.documentacionTecnicas(args);
  }

  @graphql.Query(() => DocumentacionTecnica, { nullable: true })
  async documentacionTecnica(
    @graphql.Args() args: DocumentacionTecnicaFindUniqueArgs
  ): Promise<DocumentacionTecnica | null> {
    const result = await this.service.documentacionTecnica(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => DocumentacionTecnica)
  async deleteDocumentacionTecnica(
    @graphql.Args() args: DeleteDocumentacionTecnicaArgs
  ): Promise<DocumentacionTecnica | null> {
    try {
      return await this.service.deleteDocumentacionTecnica(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
